### ISSUE TITLE
Komorebi closes the bar with `komorebic close`

### ISSUE THREAD

**Issue by FlyinCow** [amnweb/yasb#1]
When there is no other window in the workspace, `komorebic close` will unfortunately close this bar. It's annoying when you occasionally hit `alt+q` and just find your bar is gone.

**Comment by amnweb** [comment]
Actually `komorebic close' closes all focused windows, I haven't noticed these problems so far but I will fix it

**Comment by amnweb** [comment]
It should work now, please try and confirm.

**Comment by FlyinCow** [comment]
> It should work now, please try and confirm.

Great work! Thanks a lot!
