### ISSUE TITLE
Add placeholder content while fetching info

### ISSUE THREAD

**Issue by coffandro** [amnweb/yasb#14]
**What is the request?.**
I'm not on the fastest PC so sometimes it can take some time (like 10 sec) before yasb begins displaying stuff, I would love if it showed a blocky version of the bar or just some placeholder content (like a "getting data" label) before fetching content to display that it's at least kinda working

**Why is it useful?**
It would allow for showing the user that yasb is in fact working in the background.

**How could it be implemented?**
I would think maybe starting by creating the sys tray icon, then the gui and then *only* when that's present begin getting data in another thread

**Additional context**
N/A

**Comment by thomasroodnl** [comment]
I think this is a good idea, I have had a similar experience with the older yasb fork when I had some widgets that were slow (e.g. because they were doing network calls). Once media is stable I could have a go at this.
