### ISSUE TITLE
How to rename or name a workspace and dual monitors

### ISSUE THREAD

**Issue by mairm1340** [amnweb/yasb#18]
I did the python code and finally happy to see Window manager working on windows
I come from linux and was used to Window manager but forced to used windows at work.
can you advise how i can rename the work space and how i activate the start menu button.

I got dual monitors but  when i run the script it works only on one monitor

**Comment by mairm1340** [comment]
komorebi_workspaces:
  type: "komorebi.workspaces.WorkspaceWidget"
  options:
      label_offline: "Komorebi Offline"
      label_workspace_btn: "\udb81\udc3d"
      label_workspace_active_btn: "\udb81\udc3e"
      workspace_names:
        1: "Workspace 1"
        2: "Workspace 2"
        3: "Workspace 3"
        4: "Workspace 4"
        5: "Workspace 5"
        6: "Workspace 6"
        7: "Workspace 7"
        8: "Workspace 8"
      hide_empty_workspaces: false
      hide_if_offline: false
      hide_if_offline: false
      
      I did try adding this but with no luck

**Comment by markox92** [comment]
You can rename workspace in `komorebi.json `, In yasb `config.yaml` you can setup `label_workspace_btn: "{name}"` and `label_workspace_active_btn: "{name}"` to get names

**Comment by amnweb** [comment]
> You can rename workspace in `komorebi.json `, In yasb `config.yaml` you can setup `label_workspace_btn: "{name}"` and `label_workspace_active_btn: "{name}"` to get names

@mairm1340 is this working for you ?

**Comment by mairm1340** [comment]
![image](https://github.com/user-attachments/assets/6a4137b3-efbf-4d6b-ba0a-3e14363ecf24)

yes mate with the above modification it works.
I will try to learn how to colorise them :P
