### ISSUE TITLE
CPU usage reported isn't the actual CPU usage

### ISSUE THREAD

**Issue by bytenekos** [amnweb/yasb#21]
**What is the request?.**
Hi there! I've noticed that the CPU usage reported isn't the actual usage when compared to something like task manager or hwinfo

**Why is it useful?**
When looking at the CPU usage, you expect it to be accurate. Right now it's lower than what it's supposed to be

**How could it be implemented?**
I've never delved deep into hw monitoring stuff, so can't really answer anything here 😅

**Additional context**

![image](https://github.com/user-attachments/assets/961cafb5-0d38-4271-bb7b-36ca9812b912)

**Comment by amnweb** [comment]
This is how **psutil** work https://psutil.readthedocs.io/en/latest/index.html#psutil.cpu_percent
About task manager I have no idea how CPU usage is calculated and can't find any API related to this.

**Comment by bytenekos** [comment]
After doing some digging, looks like there are different ways to get the CPU usage and none of them report the same percentage back xd

Gonna close this then because seems like it's pointless
