### ISSUE TITLE
Create a desktops widget for default windows desktops

### ISSUE THREAD

**Issue by coffandro** [amnweb/yasb#22]
**What is the request?.**
I like to sometimes you Komorebi for my desktops other times use the default windows one so It'd like it if yasb could display the default windows desktops if either Komorebi isn't available or as a seperate widget

**Why is it useful?**
I open yasb without Komorebi open, it shows the workspaces from default windows

**How could it be implemented?**
[This lib allows for accessing and managing the virtual desktops, I think we could just rework komorebi to do this](https://pypi.org/project/pyvda/)

**Additional context**

**Comment by amnweb** [comment]
Done https://github.com/amnweb/yasb/commit/eb2cf38a202818f6c161503b663fa11cb0deadd9

**Comment by coffandro** [comment]
OMG, now I wish I was still on windows lol
