### ISSUE TITLE
Screen Brightness Control 

### ISSUE THREAD

**Issue by syntaxboybe** [amnweb/yasb#23]
**What is the request?.**
A clear and concise description of what the problem 
> Brightness control
**Why is it useful?**
> for fast brightness navigation
**How could it be implemented?**

**Additional context**
Add any other context or screenshots about the feature request here.m

**Comment by amnweb** [comment]
What is in your mind how this widget should look?

**Comment by syntaxboybe** [comment]
the icon looks like sun [☀️] that represents a brightness then it will change the animation base on the brightness percentage.

**Comment by amnweb** [comment]
Something like volume widget?

**Comment by syntaxboybe** [comment]
yeah
