### ISSUE TITLE
App icon.

### ISSUE THREAD

**Issue by Xiximei36** [amnweb/yasb#25]
How should I obtain the icon code for the app?

**Comment by amnweb** [comment]
> How should I obtain the icon code for the app?

What?

**Comment by Xiximei36** [comment]
Sorry, what I meant was how to get the encoding that needs to be filled in for the icon in app_list from the config.yaml file, as indicated in the picture.
![PixPin_2024-08-26_10-16-38](https://github.com/user-attachments/assets/28c3c817-661f-4b61-a2d0-9df15b870431)

**Comment by Xiximei36** [comment]
> > How should I obtain the icon code for the app?
> 
> What?

Sorry, what I meant was how to get the encoding that needs to be filled in for the icon in app_list from the config.yaml file, as indicated in the picture.
![PixPin_2024-08-26_10-16-38](https://github.com/user-attachments/assets/d242f8d2-3883-4d00-a2a6-cb0143756874)

**Comment by amnweb** [comment]
There is a nice app at https://github.com/character-map-uwp/Character-Map-UWP where you can select a font, click on icons, and copy the UTF-16 value. Alternatively, you can visit the Nerd Fonts site and do the same under the icons section.

![Screenshot 2024-08-26 043854](https://github.com/user-attachments/assets/e6e1654b-34c7-484f-961c-ace25cb50286)

**Comment by Xiximei36** [comment]
> https://github.com/character-map-uwp/Character-Map-UWP上有一个不错的应用程序，您可以在其中选择字体、单击图标并复制 UTF-16 值。或者，您可以访问 Nerd Fonts 网站并在图标部分下执行相同操作。
> 
> ![截图 2024-08-26 043854](https://private-user-images.githubusercontent.com/16545063/361286571-e6e1654b-34c7-484f-961c-ace25cb50286.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NDU4NjAsIm5iZiI6MTcyNDY0NTU2MCwicGF0aCI6Ii8xNjU0NTA2My8zNjEyODY1NzEtZTZlMTY1NGItMzRjNy00ODRmLTk2MWMtYWNlMjVjYjUwMjg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDA0MTI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3YWI5OTZmNTM4NDBiZDZiZjk5ZjM0MDBmYmYyYjZkMDUwYjk4ZTkyZjVjMzJlMDE5MTU4NDAxNmI5ZTllZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1Q8K72I7lueLr4Pdi5d2vXv7z9sS6bWlBiM35uKIWhU)
Thank you very much.
