### ISSUE TITLE
Icons dont work properly

### ISSUE THREAD

**Issue by JimmyXD2** [amnweb/yasb#29]
Hi!!!
So the Icons dont work properly, why?

![Screenshot 2024-09-07 194943](https://github.com/user-attachments/assets/e80d6800-3737-491b-afc0-2dde4cb69414)
![Screenshot 2024-09-07 195017](https://github.com/user-attachments/assets/a584cbfb-c048-4ed4-b420-3c723619039c)

OS: Windows 11 Enterprise 23h2 22631.4112
YASB version: 1.1.2
install: i installed it using winget

also, how i can make YASB look like this?:
![image](https://github.com/user-attachments/assets/8bef1b9f-e4c1-47e6-a60f-73e897c8fa2f)

without komorebi layout.

Thank you!

**Comment by amnweb** [comment]
> Hi!!! So the Icons dont work properly, why?

Missing fonts.
