### ISSUE TITLE
yasb not starting

### ISSUE THREAD

**Issue by mioscape** [amnweb/yasb#31]
I install yasb from winget, yasb cannot be opened. I don't know where's the log file

**Comment by mioscape** [comment]
> What is inside `c:\Users\{username}\.config\yasb\` ?

Ahhhh, i thought the config placement is on `c:\Users\{username}\.yasb`

**Comment by amnweb** [comment]
Problem solved?

**Comment by mioscape** [comment]
> Problem solved?

Yes, sorry for late response
