### ISSUE TITLE
[Suggestion] Switch to `Binary = True` for humanize when converting data strings

### ISSUE THREAD

**Issue by bytenekos** [amnweb/yasb#35]
I think it's better to set it to true as it matches what's reported in task manager

Examples:

`"{virtual_mem_outof}": f"{naturalsize(virtual_mem.used, True)} / {naturalsize(virtual_mem.total, True)}",`
![image](https://github.com/user-attachments/assets/19d0423f-7f0d-4fe9-9fd3-65c01dfe448c)

`"{virtual_mem_outof}": f"{naturalsize(virtual_mem.used)} / {naturalsize(virtual_mem.total)}",`
![image](https://github.com/user-attachments/assets/f014d67f-af7b-4986-afe5-78a8b04eb756)

Ram amount shown in task manager:
![image](https://github.com/user-attachments/assets/57da8393-3618-4df7-a0aa-97f776025416)

**Comment by amnweb** [comment]
Looks for some reason Microsoft and Windows have seemingly ignored the IEC/NIST and it says GB but it actually means GiB in Task Manager or I'm missing something?

**Comment by bytenekos** [comment]
Looks like it [according to this](https://www.reddit.com/r/Windows10/comments/flakzq/task_manager_memory_in_gib_or_gb/)

**Comment by amnweb** [comment]
Lol I never thought about this, but when you buy a memory you can see 16, 32GB on the box :) 
So if we use binary in `naturalsize` I'm 100% sure someone will open another issue and say "Why is memory showing GiB instead of GB xD

**Comment by bytenekos** [comment]
Easiest solution that I can think of right now would probably be to just replace GiB, with GB, etc using regex or something as dumb as this might sound (to automatically change stuff in the traffic module for example as that goes from kilobytes to megabytes, etc)

**Comment by bytenekos** [comment]
Alternatively maybe `gnu` could be used instead (it'll just be 1 letter instead of 2)

![image](https://github.com/user-attachments/assets/89d229e9-b68d-439e-95f6-a489002c7870)

**Comment by amnweb** [comment]
Fixed in https://github.com/amnweb/yasb/commit/a6619e8c0e454005b5420169a76e12a1aa4ace06
