### ISSUE TITLE
How can I learn to operate within your platform?

### ISSUE THREAD

**Issue by blvcksync** [amnweb/yasb#4]
Hi! Thanks a lot for what you've been doing. Yasb is great and seems flexible, I also love its aesthetics.
But Im **completely atrocious** in anything related to programming. Really, I just spent an hour  installing python and figuring out how to set it properly. Lol, it was like first-time linux experience to me. And now im here.
![python_TWOOYBCnna](https://github.com/user-attachments/assets/bdddf862-b54d-4ef0-99c5-5ee09b31ca75)

I'd like to customize yasb for myself (as it designed for), so it can look a bit similar to what u have here:
![msedge_SNUbMeJ9OI](https://github.com/user-attachments/assets/52199cd4-aad3-48a9-91cf-6ab7a024a3ca)

 How can I learn to navigate within config scripts (like your one) in yasb? **Do you know any  tutorials or guides related to this topic?**

**Comment by ariusxi** [comment]
I was curious about it too, the author can create a tutorial?

**Comment by amnweb** [comment]
When I have time, I'll write the Wiki; now you can try searching the documentation on the original project repo.
