### ISSUE TITLE
Hide Controls on Media Widget

### ISSUE THREAD

**Issue by n4htx** [amnweb/yasb#40]
I like the look of the media widget but there doesn't seem to be a function to hide the controls and only show the title/artwork, only the other way around. 
Any idea on a workaround or a potential fix? Thanks!

**Comment by amnweb** [comment]
You can simply hide buttons in styles.css, something like this should work. Please try and let me know.

```
.media-widget .btn {
	padding: 0;
	margin: 0;
        max-width: 0;
}
```
