### ISSUE TITLE
Support for CSS Media Queries 

### ISSUE THREAD

**Issue by S-N00B-1** [amnweb/yasb#44]
**What is the request?.**
When attempting to use CSS Media queries such as `@media (prefers-color-scheme: dark)` or `@media (prefers-color-scheme: light)`, the bar does not update as the OS colour palette is changed from 'light' to 'dark'.

**Why is it useful?**
If support for media queries is implemented, then yasb could automatically switch between a 'light' and 'dark' colour palette as defined in the `style.css`.

For example, here would be an implementation of the 'One Half' colour scheme that switches between light and dark:
```
.yasb-bar {
       transition: background-color 1s;
}
@media (prefers-color-scheme: dark) {
	.yasb-bar {background-color: rgba(40,44,52,75);}
}
@media (prefers-color-scheme: light) {
	.yasb-bar {background-color: rgba(250,250,250,75);}
}
```

**Comment by amnweb** [comment]
So dark and light should follow OS theme or what?

**Comment by S-N00B-1** [comment]
Basically.

**Comment by amnweb** [comment]
OK I can implement this but in another way, you don't need media queries. I can try to add a class for light and dark theme. So you can use `.yasb-bar.dark` or `.yasb-bar.light`. Is that enough?

**Comment by amnweb** [comment]
> Good with me

Oke... I am currently working on this.

**Comment by amnweb** [comment]
Done https://github.com/amnweb/yasb/commit/ad3529219e560bc7ec6f16c9f520599232f13459, please try and let me know if all is working.

Example:
`.yasb-bar.dark {}` target dark style bar
`.yasb-bar.dark .label {}` target dark style text

https://github.com/user-attachments/assets/adce6f91-1d7e-4ee8-9edc-a70a4d528bcb

**Comment by S-N00B-1** [comment]
Seems to work.
