### ISSUE TITLE
OBS stop recording button

### ISSUE THREAD

**Issue by im-izz** [amnweb/yasb#46]
**What is the request?.**
when starting an obs stream/recording show a button of its recording right now and if we click it, it stops recording

**Why is it useful?**
it is useful xD

**How could it be implemented?**
idrk, maybe that could run a shortcut/keybinding for obs?

**Additional context**
would be cool

**Comment by amnweb** [comment]
You mean only when you start recording to show **stop** button, otherwise do not show any button in this widget, right ?

**Comment by im-izz** [comment]
Yes only if there is recording show red REC icon that if the click it stops recording

**Comment by amnweb** [comment]
> Yes only if there is recording show red REC icon that if the click it stops recording

If OBS has some public API, we can integrate this function, I will check later.

**Comment by im-izz** [comment]
it should, since discord can detect obs and turn on the streamer mode automatically.

**Comment by amnweb** [comment]
Done https://github.com/amnweb/yasb/commit/58328fe03e7392e9873b79a0d63acfba1713a9d7
