### ISSUE TITLE
Volume icon not aligned with volume text at lower status bar heights

### ISSUE THREAD

**Issue by ykhan21** [amnweb/yasb#48]
The volume icon not aligned with volume text at lower status bar heights.

![image](https://github.com/user-attachments/assets/5781b4c6-ea1b-4d58-a060-1472d4a01ae2)

**To Reproduce**
1. Change dimensions height to 18 and padding top and bottom to 2.
2. See error

**Expected behavior**
The volume percentage should be aligned to the icon like the other widgets.

**Desktop (please complete the following information):**
 - OS: Windows 11 22631.4169
 - Brave Browser
 - YASB branch: Installed latest msi.
 - Python 3.9.13

**Comment by amnweb** [comment]
You can style this icon how you like

```
.volume-widget .icon {}
```

**Comment by ykhan21** [comment]
Also, the volume icon is much lower than the rest of the icons and has space above and not much below.

**Comment by ykhan21** [comment]
Thanks. Setting the margin to zero fixed it.
