### ISSUE TITLE
WiFi widget requires location data constantly

### ISSUE THREAD

**Issue by Video-Nomad** [amnweb/yasb#53]
**Describe the bug**
Wifi widget constantly requesting location data from windows.

**To Reproduce**
1. Add wifi widget.
2. Go to Windows Location privacy settings.
3. Expand "Recent activity" to see Network Command Shell spam.

**Expected behavior**
Simple wifi strength/status widget does not need my location.

**Screenshots**
![image](https://github.com/user-attachments/assets/961c2d98-8fd3-458b-8e6e-96f93090bdc8)

**Comment by Video-Nomad** [comment]
After going through the code it's the netsh command showing as location access. Not sure why Windows considers that as a location access but it does.

**Comment by amnweb** [comment]
Looks like `netsh wlan show interfaces` running from PowerShell needs "Let apps access your location" to be enabled to work.
Try running this command in the console `netsh wlan show interfaces` without YASB, and you will get a message from Windows that you need to enable location.
I will check that to find an alternative if there is any, but I'm afraid we can't do much against Microsoft.

**Comment by amnweb** [comment]
@Video-Nomad which OS you are using please post a `winver` screenshot?

**Comment by Video-Nomad** [comment]
@amnweb 
![image](https://github.com/user-attachments/assets/58696cf8-744c-4f95-9587-7b48e9fbb837)

**Comment by Video-Nomad** [comment]
> Looks like `netsh wlan show interfaces` running from PowerShell needs "Let apps access your location" to be enabled to work. Try running this command in the console `netsh wlan show interfaces` without YASB, and you will get a message from Windows that you need to enable location. I will check that to find an alternative if there is any, but I'm afraid we can't do much against Microsoft.

Yeah, I guess it's just Windows being extra paranoid about this specific command.

**Comment by amnweb** [comment]
Ahh yeah, that's the problem, I just checked with others on Discord and it looks like from this 24H2 release Microsoft changed this, and now to get net info you need to enable location. In 23H2, this is working without any problem. I'm also on 24H2 and here is... 

![image](https://github.com/user-attachments/assets/f3b33e85-33cd-4bab-a3f6-e23810f76d4e)

**Comment by Video-Nomad** [comment]
Got it. So it's some new security changes I guess. It's fine then. The location log spam is a bit annoying, but what can you do.

**Comment by amnweb** [comment]
@Video-Nomad please try now, I hope this commit has fixed this problem https://github.com/amnweb/yasb/commit/c39c825fd68d687576ef0847b549f4c80896a94c

**Comment by Video-Nomad** [comment]
So the NetworkInformation.get_connection_profiles() seems to be returning the history of my wifi connections and the actual connection is buried somewhere in there. I guess we need to check for network connectivity level and it should be == 3.
```py
def _get_wifi_strength(self):
    connections = NetworkInformation.get_connection_profiles()
    for connection in connections:
        if connection.is_wlan_connection_profile and connection.get_network_connectivity_level() == 3:
            signal_strength = connection.get_signal_bars()
            return signal_strength * 20
    return 0

def _get_wifi_name(self):
    connections = NetworkInformation.get_connection_profiles()
    for connection in connections:
        if connection.is_wlan_connection_profile and connection.get_network_connectivity_level() == 3:
            return connection.profile_name
    return "No WiFi"
```
This seems to be working fine. I'm not sure if there's a better way though.

**Comment by Video-Nomad** [comment]
I guess this will be a more correct approach, since we are checking for internet access anyway:
```py
def _get_wifi_strength(self):
    connections = NetworkInformation.get_connection_profiles()
    for connection in connections:
        if connection.get_network_connectivity_level() == NetworkConnectivityLevel.INTERNET_ACCESS:
            signal_strength = connection.get_signal_bars()
            return signal_strength * 20
    return 0

def _get_wifi_name(self):
    connections = NetworkInformation.get_connection_profiles()
    for connection in connections:
        if connection.get_network_connectivity_level() == NetworkConnectivityLevel.INTERNET_ACCESS:
            return connection.profile_name
    return "No WiFi"
```

**Comment by amnweb** [comment]
You're right. Updated.

**Comment by amnweb** [comment]
Also, I think we can use the `NetworkInformation.NetworkStatusChanged` and remove `update_interval` from this widget. I will check that, this could be better than a timer.

**Comment by OtterKring** [comment]
Just in case someone is still interested: this is not resolved, yet.

I just ran this in an elevated Windows Powershell 5.1 and received this error:

```
netsh wlan show interfaces

There are 2 interfaces on the system:
Network shell commands need location permission to access WLAN information. Turn on Location services on the Location page in Privacy & security settings.

Here is the URI for the Location page in the Settings app:
ms-settings:privacy-location
To open the Location page in the Settings app, hold down the Ctrl key and select the link, or run the following command:
start ms-settings:privacy-location

Or, to open the Location page from the Run dialog box, press Windows logo key + R, and then copy and paste the URI above.

Function WlanQueryInterface returns error 5:
Access is denied.
```

Location services are turned off by intune policy in our environment.

Windows Info:

```
Edition	Windows 11 Enterprise
Version	25H2
Installed on	‎30.‎10.‎2024
OS build	26200.7092
Serial number	0F39BQC24433KV
Experience	Windows Feature Experience Pack 1000.26100.253.0
```

**Comment by Video-Nomad** [comment]
@OtterKring This will not be and can't be resolved as this is new Microsoft security policy. Wi-Fi scan is considered a location access in Windows 11. No exceptions.
https://learn.microsoft.com/en-us/windows/win32/nativewifi/wi-fi-access-location-changes

**Comment by OtterKring** [comment]
ok ... well, makes sense somehow. In fact, I AM using the wifi name in a script to determine where I am, so, yes, relatable.
