### ISSUE TITLE
gWSL icons are transparent

### ISSUE THREAD

**Issue by vanchaxy** [amnweb/yasb#54]
**Describe the bug**
When running pycharm using gWSL icons in the bar are transparent.

<img width="149" alt="image" src="https://github.com/user-attachments/assets/6bc7d598-7a99-426a-ba5f-fa7ba01a9abd">

I added this to get_window_icon(), it helps but icons have a black background. (expected as they don't have transparent data at all)
```python
 _, _, _, a = img.split()
if not sum(a.getdata()):
    img.putalpha(255)
```

<img width="151" alt="image" src="https://github.com/user-attachments/assets/2214cc6d-c3b4-460c-b381-38646e0f9916">

I can submit a PR but maybe someone has a better solution without a black background. The icon looks norman in the windows toolbar:
<img width="32" alt="image" src="https://github.com/user-attachments/assets/0dbc0a38-c2d7-4d82-96ee-8e33f24aa254">

**Comment by amnweb** [comment]
I just tried to run PyCharm from WSLg and here is what I have.
![Screenshot 2024-10-15 015709](https://github.com/user-attachments/assets/3c921c3c-ee3b-4b30-bbc7-02af0dd8df26)

**Comment by vanchaxy** [comment]
@amnweb it's gwsl (https://opticos.github.io/gwsl/). Executable is GWSL_vcxsrv.exe

**Comment by amnweb** [comment]
And what is the difference between this and WSLg? I mean you can run apps from WSL.

**Comment by vanchaxy** [comment]
It uses vcxsrv instead of wslg. For me, it works faster, looks more like native app, no clipboard synchronization bug, etc.

**Comment by skyisthela** [comment]
I am not sure if this is related or not but; an image viewer I use called qimgv has the exact same issue where it doesn't show up on the active window module nor the taskbar module. I apologize in advance if these are unrelated/irrelevant.

**Comment by amnweb** [comment]
It's not related but anyway I have just tested qimgv and it seems to be related to this app. YASB cannot find standard Windows icons for this app.
