### ISSUE TITLE
Duplicate status bars when when both "*" and name are specified for screens

### ISSUE THREAD

**Issue by Testing-XYZ** [amnweb/yasb#55]
**What is the request?.**
Currently, when both "*" and name are specified, duplicate status bar is created on displays with screen_name.  It would be nice if "*" configurations only applies to displays without specified screen_name

**Why is it useful?**
In a multiple monitors setup, one might want to have one universal configuration that applies to all displays but separate configuration for specific displays.

**How could it be implemented?**
In `bar_manager.py`, have a list of all specified display and check if display is in the list when using "*" to create status bar
```
def initialize_bars(self, init=False) -> None:
        self._widget_builder = WidgetBuilder(self.config['widgets'])
        screens = [bar_config['screens'][0] for bar_name, bar_config in self.config['bars'].items()]
        for bar_name, bar_config in self.config['bars'].items():
            if bar_config['screens'] == ['*']:
                for screen in QApplication.screens():
                    if screen.name() in screens:
                        continue
                    print(screen.name())
                    self.create_bar(bar_config, bar_name, screen, init)
                continue
            for screen_name in bar_config['screens']:
                screen = get_screen_by_name(screen_name)
                if screen:
                    self.create_bar(bar_config, bar_name, screen, init)
        self.run_listeners_in_threads()
        self._widget_builder.raise_alerts_if_errors_present()
```

**Comment by amnweb** [comment]
Can't understand what you mean xD  
If you want to have a different status bar on one monitor, you should enter screen name, example `screens: ['DELL P2419H (2)']`
For multiple screens you can set up to have each monitor's own bar, bar configuration and style per monitor.

**Comment by Testing-XYZ** [comment]
> If you want to have a different status bar on one monitor, you should enter screen name, example `screens: ['DELL P2419H (2)']`

When both `screens: ['*']` and `screens: ['DELL P2419H (2)']` are present in the config, both status bars for `screens: ['*']` and `screens: ['DELL P2419H (2)']` appear on `screens: ['DELL P2419H (2)']`

**Comment by amnweb** [comment]
> > If you want to have a different status bar on one monitor, you should enter screen name, example `screens: ['DELL P2419H (2)']`
> 
> When both `screens: ['*']` and `screens: ['DELL P2419H (2)']` are present in the config, both status bars for `screens: ['*']` and `screens: ['DELL P2419H (2)']` appear on `screens: ['DELL P2419H (2)']`

I am unable to access the PC now and writing from phone

You can test something like this

```
    def initialize_bars(self, init=False) -> None:
        self._widget_builder = WidgetBuilder(self.config['widgets'])
        initialized_screens = set()

        # First, handle specific screens from config
        for bar_name, bar_config in self.config['bars'].items():
            if bar_config['screens'] != ['*']:
                for screen_name in bar_config['screens']:
                    screen = get_screen_by_name(screen_name)
                    if screen and screen_name not in initialized_screens:
                        self.create_bar(bar_config, bar_name, screen, init)
                        initialized_screens.add(screen_name)

        # Handle wildcard  ['*'] screens
        for bar_name, bar_config in self.config['bars'].items():
            if bar_config['screens'] == ['*']:
                for screen in QApplication.screens():
                    screen_name = screen.name()
                    if screen_name not in initialized_screens:
                        self.create_bar(bar_config, bar_name, screen, init)
                        initialized_screens.add(screen_name)

        self.run_listeners_in_threads()
        self._widget_builder.raise_alerts_if_errors_present()
```

**Comment by amnweb** [comment]
Updated, thanks.
