### ISSUE TITLE
Rounded corner effect lost on status bar when decreasing height

### ISSUE THREAD

**Issue by JonathanTSilva** [amnweb/yasb#61]
**Describe the bug**
When adjusting the height of the status bar in YASB to less than `36`, the rounded corner styling on the edges reverts to square corners.

**To Reproduce**
1. Edit the config.yaml
2. Change the bars.status-bar.dimensions.height to some value lower than the default `36`.
3. See the bug on taskbar, as shown in the images below:

- `bars.status-bar.dimensions.height: 36`
![image](https://github.com/user-attachments/assets/26d8ce06-ce76-4458-9069-22a4b320458e)

- `bars.status-bar.dimensions.height: 35`
![image](https://github.com/user-attachments/assets/5af82b87-6be0-4af7-a610-4d87b3c11e07)

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2 22631.4317
 - Komorebi version: 0.1.29
 - YASB version: 1.3.2

**Comment by amnweb** [comment]
This is not a bug, this is how styling works in Python. So calculation is very simple, if elements which you want to have a radius have a height of 30px the maximum radius you can apply on these elements is 15px. If you have 16px, you get the same result as you have there.
So **elements height / 2 = max radius**.

Change border radius to a lower value, and all will be fine.
