### ISSUE TITLE
Fail to communicate with Komorebi

### ISSUE THREAD

**Issue by HemiMin** [amnweb/yasb#63]
Fist, I apologize to report it as a bug, even if I am not sure it is bug or not, but there is no way to ask someone about this. 
I installed Komorebi throuth [this file](https://github.com/LGUG2Z/komorebi/releases/download/nightly/komorebi-nightly-x86_64.msi)
and then run with 
`komorebic start --whkd`
in Powershell. 

YASB installed by [this file](https://github.com/amnweb/yasb/releases/download/v1.3.5/yasb-1.3.5-win64.msi), 
and also by python as describe in [this](https://github.com/amnweb/yasb?tab=readme-ov-file#using-python).

When I run YASB with python, and executable file installed by .msi
I get "Komorebi Offline" in the status bar, 
and
"Failed to retrieve komorebi state before starting event listener: None returned. Retrying in 1 second... Is komorebi online and its binaries added to $PATH?" error. 
In $Path environment variable, komorebi/bin folder path is added. 

Can you please how I can solve it?
My OS is windows10. 
I also tried run YASB as admin, but same. 

![image](https://github.com/user-attachments/assets/abfaa9b4-fbab-4fa5-9d80-2c0c4ad4aec9)

**Comment by amnweb** [comment]
Stop Komorebi and YASB, restart PC, open terminal and type `(Get-Command komorebic.exe).Source` and tell me what is output? Then type in terminal `yasbc start` when YASB is shown type `yasbc log`, open another terminal and run `komorebic start`, wait 10 sec. and show me screenshot from both terminal.

**Comment by HemiMin** [comment]
output of `(Get-Command komorebic.exe).Source` :
`C:\Program Files\komorebi\bin\komorebic.exe`

`yasbc log`:
![image](https://github.com/user-attachments/assets/2c3c0058-792e-485a-9f20-35724edced90)

`komorebic start:`
![image](https://github.com/user-attachments/assets/c9379a7e-669a-4821-92a8-d7d1d93cfad9)

**Comment by amnweb** [comment]
What is your CPU? This looks like a timeout which is possible to happen only on very old and slow systems or YASB does not have permission to communicate with Komorebi.

**Comment by HemiMin** [comment]
CPU: Intel(R) Core(TM) Ultra 7 155H   3.80 GHz, 
I also tried YASB run in administrator mode.

**Comment by amnweb** [comment]
Did you try with the stable Komorebi release?

**Comment by HemiMin** [comment]
Yes, I installed Komorebi v0.1.29.

**Comment by amnweb** [comment]
If you want, you can try to run the Python version change this line https://github.com/amnweb/yasb/blob/6ca50c7784832b1519991dfd89ca5a6ed4cea1b9/src/core/utils/komorebi/client.py#L17 from 0.5 to something like 2, 3... and try. If this does not help, it's definitely a problem on your side with the system or something else.

**Comment by HemiMin** [comment]
Oh, now it is working! Could you apply it to the application to be installed by .msi?

**Comment by amnweb** [comment]
And also please check how long Komorebi takes to back output for this command `komorebic.exe state`?

**Comment by HemiMin** [comment]
I tried from 0.5 - 0.9, and from 0.9 it starts working.
`Measured-Command {komorebic.exe state}` output:
Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 431
Ticks             : 4316061
TotalDays         : 4.99544097222222E-06
TotalHours        : 0.000119890583333333
TotalMinutes      : 0.007193435
TotalSeconds      : 0.4316061
TotalMilliseconds : 431.6061

**Comment by amnweb** [comment]
431ms is too much, should be around 20-40ms. If I change this value, we can run into other problems. Do you have any software like antivirus or something that blocks/scans the file komorebic.exe when you run it?

**Comment by HemiMin** [comment]
Right, for the security I have so many softwares in my workspace computer. That was my problem.. I am sorry for that.

To start on boot,
If I want to run yasb with python, how can I doe that?

**Comment by amnweb** [comment]
Click on the YASB tray icon and Enable Autostart

![image](https://github.com/user-attachments/assets/5a959074-d6fe-47f9-9b97-8eb052811091)


So now all is ok between Komorebi and YASB connection ?

**Comment by HemiMin** [comment]
Yes, now it is working well.

**Comment by amnweb** [comment]
Ok great, we can close this issue.
