### ISSUE TITLE
WiFi Widget shows incorrect icon for Ethernet/Wired connections

### ISSUE THREAD

**Issue by JotaRata** [amnweb/yasb#66]
**Describe the bug**
The WiFi widget icon shows an incorrect placeholder icon when the user is connected through a wired network (e.g. Ethernet)
The icon itself doesn't seem to come from the widget configuration in the .yaml file but instead is placed there as a placeholder using the icon of a fully charged battery instead, regardless of the signal strength icon choice..

**To Reproduce**
1. Use a wired connection, per example a mobile phone with USB tethering mode on.

**Expected behavior**
A special Ethernet icon such as \udb83\udc9d should appear.

**Screenshots**
Current issue:
![imagen](https://github.com/user-attachments/assets/9b6f4240-8015-4c47-88c4-e211e8911941)

Possible icon to use:
![imagen](https://github.com/user-attachments/assets/8cd52a48-f633-4f21-85a0-be757e02c4d9)

**Comment by amnweb** [comment]
Can you tell me which font use have defined inside styles.css ?

**Comment by JotaRata** [comment]
Changing the font family specifically for `.wifi-widget .icon` to ""JetBrainsMono NFP" fixed the issue. I'm using the Aura theme which for some reason have lots of different font families for different widgets.
Thanks
