### ISSUE TITLE
Clubbing two widgets together

### ISSUE THREAD

**Issue by Legend0804** [amnweb/yasb#76]
Is there any way to club two widgets together?
![image](https://github.com/user-attachments/assets/38d6d5ba-dfcd-4d27-8d65-615e5145c15e)

Like, I'd like to have wifi and bluetooth in one block and volume and time-date in another. As per my knowledge, I can either put all 4 widgets in one block or put all 4 in separate ones

**Comment by amnweb** [comment]
This can be done with css, set margin or padding to 0 for this widget
