### ISSUE TITLE
ICONS ARE NOT SHOWING

### ISSUE THREAD

**Issue by Yusuf0078** [amnweb/yasb#86]
I browsed the forum a little bit about this problem and they said it was due to a font deficiency. I downloaded it but the situation did not change and I do not know how to set the themes.
![image](https://github.com/user-attachments/assets/24b436b0-a3fd-44a2-a947-719f79b18197)

**Comment by amnweb** [comment]
It's a font.
Which font you have set in styles.css?

**Comment by Yusuf0078** [comment]
[styles.zip](https://github.com/user-attachments/files/18200510/styles.zip)
Actually I didn't set it up at all, I sent the file thinking there might be an error.

**Comment by amnweb** [comment]
And you have installed `JetBrainsMono NFP` font? I can see text on your bar that is not `JetBrains` font.

**Comment by Yusuf0078** [comment]
I downloaded the jet brians file and it turned out to be more than one font file, only the variable folder

**Comment by Yusuf0078** [comment]
I only downloaded the files in the variable folder

**Comment by amnweb** [comment]
From where you download this fonts?

**Comment by Yusuf0078** [comment]
https://fonts.google.com/specimen/JetBrains+Mono

(I may be making a typo, I am writing from translation.)

**Comment by amnweb** [comment]
> https://fonts.google.com/specimen/JetBrains+Mono
> 
> (I may be making a typo, I am writing from translation.)

![Screenshot_20241219_183418_GitHub.jpg](https://github.com/user-attachments/assets/f08f1a8e-1841-4e42-9412-4135f7f7736f)
