### ISSUE TITLE
Application icon support for the Applications widget

### ISSUE THREAD

**Issue by Osyx** [amnweb/yasb#89]
**What is the request?.**
It would be great if I could use the apps widget without specifying icons, and then get the actual .exe icon (e.g. the ones shown in the taskbar widget). 
Either that, or to be able to specify the paths to either the .exe or an .ico/.png file as the icon property and have that be shown.
Or both of those options!

**Why is it useful?**
Not all applications have icons specified in the Nerd Fonts, sometimes you want the native icon, and sometimes you want colored icons without having to customize all of them via CSS.

**How could it be implemented?**
Something like this:
![image](https://github.com/user-attachments/assets/64a4e2a9-9637-40e3-b3a2-11b95dc5446e)
![image](https://github.com/user-attachments/assets/3a3c52dc-7fac-467d-9978-c067641abdba)

**Additional context**
See discussion [here](https://discord.com/channels/898554690126630914/1001847171861196800/1322008821539012670) on Discord for more context.

**Comment by amnweb** [comment]
Done https://github.com/amnweb/yasb/commit/eec1e27cfc52e88298dd5bcbe5092a4653846630 Wiki https://github.com/amnweb/yasb/wiki/(Widget)-Applications
