### ISSUE TITLE
hide_taskbar: - unknown field

### ISSUE THREAD

**Issue by Testing-XYZ** [amnweb/yasb#92]
**Describe the bug**
When I add hide_taskbar: true to config.yaml, the error with details "hide_taskbar: - unknown field" pops up

**To Reproduce**
1. Install yasb v1.5.1 via winget
2. Add `hide_taskbar: true` after 
`watch_stylesheet: true`
`watch_config: true`
3. Got error "Yasb: Failed to load recently updated config file". 

**Expected behavior**
Config should work and hides the taskbar. 

**Desktop (please complete the following information):**
 - OS: Windows 11 26100.2605
 - YASB v1.5.1

**Comment by amnweb** [comment]
Can you show me your config ?

**Comment by Testing-XYZ** [comment]
> Note: Also did you read this #82 ?
Ok It appears that the older version was not removed and `yasbc --version` only shows the latest installation. The config works after removing  the older version.

**Comment by hcaginlenk** [comment]
I am receiving the same error as mentioned in this issue:
`hide_taskbar:- unknown field`

Yasb version: v1.8.2 (stable)

config attached.

[yasb_configtxt.txt](https://github.com/user-attachments/files/22592126/yasb_configtxt.txt)

**Comment by amnweb** [comment]
> hide_taskbar

`hide_taskbar` is removed from YASB 6 month ago.
